### PR TITLE
Fmt

### PR DESCRIPTION
**Pull request by ArshErgon**
Add a `cargo fmt` checker to check whether the file is formatted or not.
refactor multi line code in single line for better readability
did some small updation on docs

### CODE REVIEW

**Comment by mamaicode** [comment]
@ArshErgon Hello! Thank you so much for looking over the project and contributing!
I appreciate it a lot.

I would like to ask you to remove the following line from the yml file:
`token: ${{ secrets.GITHUB_TOKEN }}`

I don't think it is necessary ~
Let me know if you think otherwise!

**Comment by ArshErgon** [comment]
> @ArshErgon Hello! Thank you so much for looking over the project and contributing! I appreciate it a lot.
> 
> I would like to ask you to remove the following line from the yml file: `token: ${{ secrets.GITHUB_TOKEN }}`
> 
> I don't think it is necessary ~ Let me know if you think otherwise!

well, its not gonna work if I remove the `token` in my understanding its safe using that.

**Comment by mamaicode** [comment]
@ArshErgon Thank you once again! 🦀❤️

**Comment by ArshErgon** [comment]
@scirin thanks for the merge.
And I will be contributing more in your projects I have gone through your projects, I can learn so much for you.
Thanks again

**Pull request merged**
